### ISSUE TITLE
k8s pod connectivity problem

### ISSUE THREAD

**Issue by gothub** [NCEAS/metadig-engine#288]
@mbjones @nickatnceas 

On the production k8s cluster, the 2 worker nodes that have been upgraded for CephFS cannot communicate with the control node at the pod level. Here is the current status:

docker-ucsb-4: control node
docker-ucsb-5: worker, upgraded for CephFS, pods cannot communicate with pods on other nodes
docker-ucsb-6: worker, upgraded for CephFS, pods cannot communicate with pods on other nodes
docker-ucsb-7: worker, not upgraded for CephFS, pods can communicate with pods on other nodes

Both metadig-engine pods and generic pods (i.e. dns test pod) were used to confirm the issue on each worker node.

The node outages on the two worker nodes coincides with the CephFS upgrades, but I haven't found a cause yet,
so cannot say the the upgrade is definitely the cause. However, it would be helpful to get input on anything y'all
might think could be contributing.

Here is some background:
Our k8s cluster uses an overlay network managed by the k8s plugin [calico](https://docs.projectcalico.org/getting-started/kubernetes/) for communication between pods and manages IP addresses in the range 192.168.0.0/16.

k8s itself manages an overlay network for services with the IP range 10.96.0.0/12. This does not overlap with the
ufw rule added for CephFS (seen with 'sudo ufw status'):

     Anywhere                   ALLOW       10.0.3.0/24

k8s and calico both manipulate iptables to establish routes between pods and services, so any firewall applications such
as IceFloor or NetworkManager can prevent them from working. I don't see these apps installed.

Here is the info from the calico management program 'calicoctl' that shows the trouble it is having. First I'll show the output for the node that works (docker-ucsb-7), then a node that does not (docker-ucsb-5):

docker-ucsb-7:
```
sudo -E ./calicoctl node status
Calico process is running.

IPv4 BGP status
+----------------+-------------------+-------+------------+-------------+
|  PEER ADDRESS  |     PEER TYPE     | STATE |   SINCE    |    INFO     |
+----------------+-------------------+-------+------------+-------------+
| 128.111.85.192 | node-to-node mesh | up    | 2021-05-28 | Established |
| 10.0.3.196     | node-to-node mesh | start | 2021-05-28 | Connect     |
| 10.0.3.193     | node-to-node mesh | start | 2021-05-28 | Connect     |
+----------------+-------------------+-------+------------+-------------+

IPv6 BGP status
No IPv6 peers found.
```
docker-ucsb-5:
```
sudo -E ./calicoctl node status
Calico process is running.

IPv4 BGP status
+----------------+-------------------+-------+------------+-------------+
|  PEER ADDRESS  |     PEER TYPE     | STATE |   SINCE    |    INFO     |
+----------------+-------------------+-------+------------+-------------+
| 128.111.85.192 | node-to-node mesh | start | 2021-05-31 | Passive     |
| 10.0.3.196     | node-to-node mesh | up    | 15:22:43   | Established |
| 128.111.85.225 | node-to-node mesh | start | 2021-05-31 | Passive     |
+----------------+-------------------+-------+------------+-------------+

IPv6 BGP status
No IPv6 peers found.
```

Any ideas on what may be causing the issue, or additional things to try?

**Comment by mbjones** [comment]
Thanks for the summary @gothub. I'm not sure what "Connect", "Established", and "Passive" mean in the those tables. Do you have a pointer to where they are documented? I think one thing I would immediately check is if you have network connectivity from and to each of the affected nodes on ports that should be open to each other. If not, then maybe its just firewall or route configuration issues. Have you tested that connectivity?

**Comment by mbjones** [comment]
Here's the complete Calico status for nodes 4-7:

## docker-ucsb-4

Calico process is running.

IPv4 BGP status
+----------------+-------------------+-------+------------+-------------+
|  PEER ADDRESS  |     PEER TYPE     | STATE |   SINCE    |    INFO     |
+----------------+-------------------+-------+------------+-------------+
| 10.0.3.193     | node-to-node mesh | start | 2021-05-31 | Connect     |
| 10.0.3.196     | node-to-node mesh | start | 2021-05-31 | Connect     |
| 128.111.85.225 | node-to-node mesh | up    | 2021-05-31 | Established |
+----------------+-------------------+-------+------------+-------------+

IPv6 BGP status
No IPv6 peers found.


## docker-ucsb-5

Calico process is running.

IPv4 BGP status
+----------------+-------------------+-------+------------+-------------+
|  PEER ADDRESS  |     PEER TYPE     | STATE |   SINCE    |    INFO     |
+----------------+-------------------+-------+------------+-------------+
| 128.111.85.192 | node-to-node mesh | start | 2021-05-31 | Passive     |
| 10.0.3.196     | node-to-node mesh | up    | 15:22:43   | Established |
| 128.111.85.225 | node-to-node mesh | start | 2021-05-31 | Passive     |
+----------------+-------------------+-------+------------+-------------+

IPv6 BGP status
No IPv6 peers found.

## docker-ucsb-6

Calico process is running.
IPv4 BGP status
+----------------+-------------------+-------+----------+-------------+
|  PEER ADDRESS  |     PEER TYPE     | STATE |  SINCE   |    INFO     |
+----------------+-------------------+-------+----------+-------------+
| 128.111.85.192 | node-to-node mesh | start | 15:22:41 | Passive     |
| 10.0.3.193     | node-to-node mesh | up    | 15:22:43 | Established |
| 128.111.85.225 | node-to-node mesh | start | 15:22:41 | Passive     |
+----------------+-------------------+-------+----------+-------------+
IPv6 BGP status
No IPv6 peers found.

## docker-ucsb-7

Calico process is running.

IPv4 BGP status
+----------------+-------------------+-------+------------+-------------+
|  PEER ADDRESS  |     PEER TYPE     | STATE |   SINCE    |    INFO     |
+----------------+-------------------+-------+------------+-------------+
| 128.111.85.192 | node-to-node mesh | up    | 2021-05-31 | Established |
| 10.0.3.193     | node-to-node mesh | start | 2021-05-31 | Connect     |
| 10.0.3.196     | node-to-node mesh | start | 2021-05-31 | Connect     |
+----------------+-------------------+-------+------------+-------------+

IPv6 BGP status
No IPv6 peers found.

**Comment by gothub** [comment]
Here is a synopsis of the problem cause and the solution determined by @mbjones @nickatnceas and @gothub.

Our k8s clusters (prod and dev) use the k8s [CNI plugin](https://rancher.com/blog/2019/2019-03-21-comparing-kubernetes-cni-providers-flannel-calico-canal-and-weave/) `calico` to manage the  overlay network IP addresses and establish connections between pods. When k8s is initially installed, the overlay network cidr to use is specified:
```
     sudo kubeadm init --pod-network-cidr=192.168.0.0/16
```

In addition, calico needs to know the IP network that k8s controller and worker nodes are on, which it determines by
 "discovering`"them. The problem was that calico was "discovering" the IP network that was newly added for the CephFS upgrade, which is 10.0.3.0/24. The network that should have been used is 128.111.85.0/24.

(I'm assuming that this discovery process is needed as calico can operate on many different network configurations.)

To control the IP network and nodes that calico uses, a the node resource can be modified for each node in the network that specifies the IP address. In our case, the alternative method is to specify a different discovery mechanism  for calico
to use:
```
kubectl set env daemonset/calico-node -n kube-system IP_AUTODETECTION_METHOD=can-reach=128.111.85.1
```

(See https://docs.projectcalico.org/networking/ip-autodetection#change-the-autodetection-method for more details)

After the above command is entered (with the k8s admin config context), calico has discovered the correct IPs:
```
metadig@docker-ucsb-4:~/deployments/calico-3.19.1$ sudo -E ./calicoctl node status
Calico process is running.

IPv4 BGP status
+----------------+-------------------+-------+----------+-------------+
|  PEER ADDRESS  |     PEER TYPE     | STATE |  SINCE   |    INFO     |
+----------------+-------------------+-------+----------+-------------+
| 128.111.85.225 | node-to-node mesh | up    | 22:59:05 | Established | (docker-ucsb-7)
| 128.111.85.193 | node-to-node mesh | up    | 22:58:17 | Established | (docker-ucsb-5)
| 128.111.85.196 | node-to-node mesh | up    | 15:38:41 | Established | (docker-ucsb-6)
+----------------+-------------------+-------+----------+-------------+
```
