### ISSUE TITLE
Use case for  running checks locally?

### ISSUE THREAD

**Issue by gothub** [NCEAS/metadig-engine#51]
It would be very useful to be able to author/run checks in the
check language (R, python) for checks that exist locally and have
not yet been registered with mdqe. This would aid developing checks
and would not require check writers to work in a Java development
environment.

For R, for example, the metadig-r library could be extended so that
a local check could be submitted to mdqe and 'staged', not run, so
that the necessary environment is passed back to R (selected variables),
then the check is initialized and run locally. This would entail changes to
the webapp and mdqe to support a new service, maybe 'check/stage'.

Thoughts?

**Comment by mbjones** [comment]
I think this would be very helpful.  As an alternative launch process, we could easily use the data identifiers requested to download the metadata and data, run the xpaths, and fire the checks locally.  This would require no involvement from the java engine, and only really rely on the DataONE API.  Let's discuss this further when @amoeba returns.

**Comment by gothub** [comment]
BTW, this is related to the current use case 20 - "Run recommendation locally in R".

**Comment by leinfelder** [comment]
To me this sounds like "reimplement the MDQ engine in R"

**Comment by mbjones** [comment]
Yep.  But it is a powerful design goal, and will empower data managers to build and contribute checks. That's why I added use case 20 in the first place, and I think its important. Luckily, there is little involved in running a check (download metadata and data using existing dataone libs, apply xpath selectors, and call the check function), and so it shouldn't be burdensome. I think the benefits will far outweigh the costs.

**Comment by jeanetteclark** [comment]
there are a few ways to run single checks or suites locally so I'm going to close this
